### ISSUE TITLE
Compiled Pyton fails to import PyTorch

### ISSUE THREAD

**Issue by nbigaouette** [nbigaouette/pycors#60]
Using a compiled-by-pycors interpreter breaks imports of PyTorch.

For example:

```
> pycors -V
0.1.7
> pycors install =3.7.2
[...]
> pycors select =3.7.2
[...]
> python -m venv .venv
[...]
> source .venv/bin/activate
> pip install torch torchvision
[...]
> python -c "import torch; print(torch.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/ghissue/.venv/lib/python3.7/site-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ModuleNotFoundError: No module named 'torch._C'
```

Using an official build from python.org, it works:

```
> ln -s /Library/Frameworks/Python.framework/Versions/3.7 ~/.pycors/installed/3.7.3-prebuilt
> pycors select =3.7.3-prebuilt
[...]
> python -m venv .venv
[...]
> source .venv/bin/activate
> pip install torch torchvision
[...]
> python -c "import torch; print(torch.__version__)"
1.0.1.post2
```

There seems to be a problem in the compilation process...

**Comment by nbigaouette** [comment]
Could it be caused by an ABI mismatch between the pycors-compiled version of Python and PyTorch's pre-built wheel?

**Comment by nbigaouette** [comment]
Interestingly, it's possible to install pytorch using the prebuilt interpreter then switch to a pycors-built one and the virtual env will work:

```
> pycors select =3.7.3-prebuilt
> python -V
Python 3.7.3
> python -m venv venv-3.7.3-prebuilt
> source venv-3.7.3-prebuilt/bin/activate
> pip install torch
> python -c 'import torch; print(torch.__version__)'
1.0.1.post2
> pycors select =3.7.2
> python -V
Python 3.7.2
> python -c 'import torch; print(torch.__version__)'
1.0.1.post2
```

**Comment by nbigaouette** [comment]
Copying the `site-packages` from a pre-built's virtualenv to a pycors' built is not working:

```sh
> pycors select =3.7.3-prebuilt
> python -V
Python 3.7.3
> python -m venv venv-3.7.3-prebuilt
> source venv-3.7.3-prebuilt/bin/activate
> python -V
Python 3.7.3
> pip install torch numpy
> python -c 'import torch; print(torch.__version__)'
1.0.1.post2

> deactivate

> pycors select =3.7.2
> python -V
Python 3.7.2
> python -m venv venv-3.7.2
> source venv-3.7.2/bin/activate
> python -V
Python 3.7.2
> mv venv-3.7.2/lib/python3.7/site-packages{,.bak}
> cp -r venv-3.7.3-prebuilt/lib/python3.7/site-packages venv-3.7.2/lib/python3.7/site-packages
> python -c 'import torch; print(torch.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv-3.7.2/lib/python3.7/site-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ModuleNotFoundError: No module named 'torch._C'
```

That's another indication that the problem is with the interpreter...

**Comment by nbigaouette** [comment]
Running `configure` manually revealed something interesting. On the left, 

```
> diff configure_manual_working.log configure_pycors_notworking.log
[...]
651,652c651,652
< checking ABIFLAGS... m
< checking SOABI... cpython-37m-darwin
---
> checking ABIFLAGS... dm
> checking SOABI... cpython-37dm-darwin
```

**Comment by nbigaouette** [comment]
Manual compilation (can import pytorch fine):
```
 -> ./python.exe -m sysconfig | rg -i abi
	ABIFLAGS = "m"
	SGI_ABI = "@SGI_ABI@"
	SOABI = "cpython-37m-darwin"
	abiflags = "m"
```

Pycors-compiled interpreter:
```
python -m sysconfig | rg -i abi
	ABIFLAGS = "dm"
	SGI_ABI = "@SGI_ABI@"
	SOABI = "cpython-37dm-darwin"
	abiflags = "dm"
```

**Comment by nbigaouette** [comment]
Urg... ABI issue. See https://www.python.org/dev/peps/pep-3149/
```

    --with-pydebug (flag: d)
    --with-pymalloc (flag: m)
    --with-wide-unicode (flag: u)
```

The flag `--with-pydebug` should probably not be used!
